# Generated by Django 6.0.7 on 2026-07-11 08:31

import autoslug.fields
import django.db.models.deletion
import django_ckeditor_5.fields
import loevtcson.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=loevtcson.models.instance_title, slugify=loevtcson.models.slugify_value, unique=True)),
                ('director', models.CharField(db_index=True, max_length=255, verbose_name='Руководитель')),
                ('cabinet', models.IntegerField(verbose_name='Номер кабинета')),
                ('address', models.CharField(db_index=True, max_length=255, verbose_name='Юридический адрес')),
                ('telephone', models.CharField(db_index=True, max_length=255, verbose_name='Телефон')),
                ('info', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Информация')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание')),
                ('photo', models.ImageField(upload_to='about', verbose_name='Фото')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Раздел')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=loevtcson.models.instance_title, slugify=loevtcson.models.slugify_value, unique=True)),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия события')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описания события')),
                ('color', models.CharField(default='#3788d8', max_length=7, verbose_name='цвет события в календаре')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Url-адрес')),
                ('logo', models.ImageField(upload_to='footer_logo_url', verbose_name='Логотип для ссылки')),
                ('show', models.BooleanField(default=True, verbose_name='Показать')),
            ],
            options={
                'verbose_name': 'Ссылка для подвала',
                'verbose_name_plural': 'Ссылки для подвала',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=loevtcson.models.news_photo_upload_path, verbose_name='Фото')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='ContentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=loevtcson.models.instance_title, slugify=loevtcson.models.slugify_value, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='loevtcson.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Содержание раздела',
                'verbose_name_plural': 'Содержания разделов',
            },
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=loevtcson.models.content_file_upload_path, verbose_name='Файл')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла, которое будет показано на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='loevtcson.contentchapter', verbose_name='Содержание раздела')),
            ],
            options={
                'verbose_name': 'Прикреплённый файл',
                'verbose_name_plural': 'Прикреплённые файлы',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=loevtcson.models.news_image_upload_path, verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loevtcson.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фото для новости',
            },
        ),
    ]
